name: Deploy my app on the vps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  Testing and deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install

      - name: Run test
        run: yarn test

      - name: Copy files to the VPS via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./"
          target: "/opt/techstore"
          strip_components: 0

      - name: Deploy on th server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/techstore
            docker build -t todo-app .
            docker stop todo-app || true
            docker rm todo-app || true
            docker run -d --name todo -p 3000:3000 todo-app


