name: Deploy my app on the vps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name : Testing something
        run: echo "Hello world"
